const fs = require('fs');
const path = require('path');
const { Client } = require('pg');

function loadEnv(envPath) {
  const text = fs.readFileSync(envPath, 'utf8');
  const lines = text.split(/\r?\n/);
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx);
    const val = trimmed.slice(idx + 1);
    env[key] = val;
  }
  return env;
}

(async () => {
  try {
    const repoRoot = path.resolve(__dirname, '..');
    const env = loadEnv(path.join(repoRoot, '.env.local'));

    const dbUrl = env.DATABASE_URL;
    if (!dbUrl) {
      console.error('Missing DATABASE_URL in .env.local. Please add your Supabase Postgres connection string.');
      process.exit(1);
    }

    const client = new Client({ connectionString: dbUrl });
    await client.connect();

    const sql = `
      create table if not exists public.services (
        id bigint generated by default as identity primary key,
        title text not null,
        description text not null,
        image_url text not null,
        created_at timestamptz default now() not null
      );

      create table if not exists public.media_items (
        id bigint generated by default as identity primary key,
        title text not null,
        description text,
        image_url text not null,
        category text not null,
        created_at timestamptz default now() not null
      );
    `;

    console.log('Creating missing tables: services, media_items');
    await client.query(sql);
    console.log('Tables created successfully.');
    await client.end();
    process.exit(0);
  } catch (error) {
    console.error('Error creating tables:', error.message || error);
    process.exit(1);
  }
})();